name: pulse_instagram
description: Professional Instagram-style social app with YouTube Shorts, Stories, Chats, WebRTC. Legal public data only.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^14.2.0

  # Video / Reels / YouTube
  video_player: ^2.9.1
  chewie: ^1.8.1
  youtube_player_iframe: ^5.1.2
  http: ^1.2.2

  # WebRTC + Permissions
  flutter_webrtc: ^1.0.0
  permission_handler: ^11.3.1

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  firebase_database: ^11.1.4

  # Utils
  intl: ^0.19.0
  uuid: ^4.4.2
  timeago: ^3.6.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
